apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
    - ../../base
    - config.yaml

images:
    -   name: bikramtuladhar/mern-react
        newName: bikramtuladhar/mern-react
        newTag: latest
