apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
    - ../../base
    - config.yaml
    - ingress.yaml

images:
    -   name: bikramtuladhar/mern-react
        newName: bikramtuladhar/mern-react-staging
        newTag: latest
