apiVersion: apps/v1
kind: Deployment
metadata:
    name: mern-frontend
    labels:
        tier: frontend
        layer: appserver
spec:
    selector:
        matchLabels:
            tier: frontend
            layer: appserver
    replicas: 1
    template:
        metadata:
            labels:
                tier: frontend
                layer: appserver
        spec:
            containers:
                -   name: frontend
                    envFrom:
                        -   configMapRef:
                                name: frontend-config
                    image: bikramtuladhar/mern-react:latest
                    imagePullPolicy: Always
                    ports:
                        -   containerPort: 3000
                            name: http-port
                    securityContext:
                        allowPrivilegeEscalation: false
                        privileged: false
            securityContext:
              { }
