apiVersion: v1
kind: Service
metadata:
    name: frontend
spec:
    ports:
        - port: 3000
          targetPort: http-port
          protocol: TCP
    selector:
        tier: frontend
        layer: appserver
