apiVersion: v1
kind: Service
metadata:
    name: backend-service
spec:
    ports:
        - port: 8080
          targetPort: http-port
          protocol: TCP
    selector:
        tier: backend
        layer: appserver
