apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
    - ../../base
    - config.yaml
    - secret.yaml

images:
    -   name: bikramtuladhar/mern-express
        newName: bikramtuladhar/mern-express
        newTag: latest
